package br.dev.ferreiras.challenges.leetcode;

import java.util.ArrayList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Queue;

/**
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * Return the letter that was added to t.
 * Example 1:
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * Example 2:
 * Input: s = "", t = "y"
 * Output: "y"
 */
public class FindDifference {
  public static void main(String[] args) {
    String s = "abcd";
    String t = "abcde";
    System.out.println(findDifference(s, t));
  }

  public static char findTheDifference(String s, String t) {
    char response = ' ';
    Queue<Character> queue = new PriorityQueue<>((x, y) -> x - y);
    for (char x : t.toCharArray()) {
      queue.add(x);
    }
    int i = 0;
    while (!queue.isEmpty()) {
      if (s.charAt(i) == queue.peek()) {
        queue.remove();
        i++;
      } else {
        response = queue.remove();
      }
    }
    return response;
  }

  public static char findingDifference(String s, String t) {
    char response = ' ';
    List<Character> queue = new ArrayList<>();
    for (char x : s.toCharArray()) {
      queue.add(x);
    }
    for (int i = 0; i < t.length(); i++) {
      if (!queue.contains(t.charAt(i))) {
        return t.charAt(i);
      }
    }
    return ' ';
  }

  public static char findDifference(String s, String t) {
    char ch = 0;
    for (char c : s.toCharArray())
      ch ^= c;
    for (char d : t.toCharArray())
      ch ^= d;
    return ch;
  }
}
